apiVersion: v1
kind: ConfigMap
metadata:
  name: phrydlpg-config
data:
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "phrydlpg"
  MINIO_URL: "http://minio.storage.svc.cluster.local:9000"
  MINIO_BUCKET: "phrydlpg-assets"
