apiVersion: v1
kind: Secret
metadata:
  name: phrydlpg-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "secure_postgres_password"
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "secure_minio_password"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
