create table audit_logs (timestamp timestamp(6), id uuid not null, details varchar(1000), action varchar(255) not null, entity_id varchar(255) not null, entity_type varchar(255) not null, performed_by varchar(255), primary key (id));
create table bed_allocations (deposit_amount numeric(38,2), end_date date, rent_amount numeric(38,2), start_date date not null, created_at timestamp(6), updated_at timestamp(6), bed_id uuid not null, id uuid not null, tenant_id uuid not null, status varchar(255) not null, primary key (id));
create table beds (created_at timestamp(6), updated_at timestamp(6), id uuid not null, room_id uuid not null, bed_number varchar(255) not null, status varchar(255), primary key (id));
create table complaints (created_at timestamp(6), updated_at timestamp(6), assignee_id uuid, id uuid not null, property_id uuid not null, tenant_id uuid not null, description TEXT, priority varchar(255) not null, status varchar(255), ticket_ref varchar(255) not null unique, title varchar(255) not null, primary key (id));
create table expenses (amount numeric(38,2) not null, expense_date date not null, created_at timestamp(6), updated_at timestamp(6), id uuid not null, property_id uuid, bill_url varchar(255), category varchar(255) not null, description varchar(255), status varchar(255), title varchar(255) not null, primary key (id));
create table feature_toggles (is_enabled boolean not null, created_at timestamp(6), updated_at timestamp(6), id uuid not null, description varchar(255), feature_key varchar(255) not null unique, primary key (id));
create table invoice_line_items (amount numeric(38,2) not null, created_at timestamp(6), updated_at timestamp(6), id uuid not null, invoice_id uuid not null, description varchar(255) not null, primary key (id));
create table invoices (amount numeric(38,2) not null, due_date date not null, late_fee_applied numeric(38,2), total_amount numeric(38,2) not null, created_at timestamp(6), updated_at timestamp(6), id uuid not null, property_id uuid not null, tenant_id uuid not null, billing_month varchar(255) not null, invoice_number varchar(255) not null unique, status varchar(255) not null check (status in ('DRAFT','GENERATED','PENDING','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED')), primary key (id));
create table kyc_documents (updated_at timestamp(6), uploaded_at timestamp(6), verified_at timestamp(6), id uuid not null, tenant_id uuid not null, verified_by uuid, document_url varchar(1000) not null, document_type varchar(255) not null, status varchar(255) not null, primary key (id));
create table landing_page_events (id bigserial not null, timestamp timestamp(6), source varchar(255), title varchar(255), type varchar(255), primary key (id));
create table leads (move_in_date date not null, created_at timestamp(6), updated_at timestamp(6), additional_requirements varchar(1000), remarks varchar(2000), assigned_to varchar(255), email varchar(255) not null, full_name varchar(255) not null, gender varchar(255) not null, id varchar(255) not null, mobile_number varchar(255) not null, occupation varchar(255) not null, preferred_location varchar(255) not null, room_type varchar(255) not null, source varchar(255) not null, status varchar(255) not null, primary key (id));
create table notices (created_at timestamp(6), updated_at timestamp(6), author_id uuid not null, id uuid not null, property_id uuid not null, content varchar(5000) not null, title varchar(255) not null, primary key (id));
create table notifications (is_read boolean not null, created_at timestamp(6) not null, id uuid not null, user_id uuid not null, message varchar(1000) not null, title varchar(255) not null, type varchar(255) not null, primary key (id));
create table payments (amount numeric(38,2) not null, created_at timestamp(6), payment_date timestamp(6), updated_at timestamp(6), id uuid not null, invoice_id uuid not null, failure_reason varchar(255), gateway_order_id varchar(255), gateway_payment_id varchar(255), gateway_signature varchar(255), method varchar(255), status varchar(255) check (status in ('PENDING','SUCCESS','FAILED','REFUNDED')), transaction_ref varchar(255) not null unique, type varchar(255) not null, primary key (id));
create table properties (capacity integer not null, created_at timestamp(6), updated_at timestamp(6), id uuid not null, manager_id uuid, region_id uuid, address TEXT not null, contact_phone varchar(255), name varchar(255) not null, slug varchar(255) not null unique, status varchar(255), type varchar(255), whatsapp_number varchar(255), primary key (id));
create table property_amenities (property_id uuid not null, amenity varchar(255));
create table property_images (property_id uuid not null, image_url varchar(255));
create table refresh_tokens (expiry_date timestamp(6) with time zone not null, id uuid not null, user_id uuid unique, token varchar(255) not null unique, primary key (id));
create table refunds (amount numeric(38,2) not null, created_at timestamp(6), requested_at timestamp(6), updated_at timestamp(6), approved_by_id uuid not null, id uuid not null, payment_id uuid not null, reason TEXT, status varchar(255) not null, primary key (id));
create table regions (created_at timestamp(6), updated_at timestamp(6), id uuid not null, region_manager_id uuid, description varchar(255), name varchar(255) not null, primary key (id));
create table rooms (created_at timestamp(6), updated_at timestamp(6), id uuid not null, property_id uuid not null, room_number varchar(255) not null, status varchar(255), type varchar(255) not null, primary key (id));
create table settings (grace_period_days integer not null, late_fee_value numeric(38,2) not null, created_at timestamp(6), updated_at timestamp(6), id uuid not null, late_fee_type varchar(255) not null, primary key (id));
create table tenant_ledgers (amount numeric(38,2) not null, balance numeric(38,2) not null, created_at timestamp(6), id uuid not null, invoice_id uuid, payment_id uuid, tenant_id uuid not null, description varchar(255), transaction_type varchar(255) not null check (transaction_type in ('CREDIT','DEBIT')), primary key (id));
create table tenants (age integer, lease_end date, lease_start date, monthly_rent numeric(38,2) not null, security_deposit numeric(38,2) not null, created_at timestamp(6), updated_at timestamp(6), bed_id uuid, id uuid not null, user_id uuid unique, emergency_contact varchar(255), employer_or_college varchar(255), kyc_status varchar(255), lead_id varchar(255) unique, occupation varchar(255), permanent_address varchar(255), status varchar(255), tenant_code varchar(255) not null unique, primary key (id));
create table users (created_at timestamp(6), updated_at timestamp(6), id uuid not null, email varchar(255) not null unique, first_name varchar(255), last_name varchar(255), password_hash varchar(255) not null, phone_number varchar(255), role varchar(255) not null check (role in ('SUPER_ADMIN','ADMIN','REGION_MANAGER','MANAGER','STAFF','TENANT')), status varchar(255) not null, primary key (id));
create index idx_complaint_status on complaints (status);
create index idx_complaint_created_at on complaints (created_at);
create index idx_complaint_tenant_id on complaints (tenant_id);
create index idx_complaint_property_id on complaints (property_id);
create index idx_invoice_tenant_id on invoices (tenant_id);
create index idx_invoice_created_at on invoices (created_at);
create index idx_invoice_status on invoices (status);
create index idx_payment_invoice_id on payments (invoice_id);
create index idx_payment_created_at on payments (created_at);
create index idx_payment_status on payments (status);
create index idx_room_property_id on rooms (property_id);
create index idx_tenant_user_id on tenants (user_id);
create index idx_tenant_bed_id on tenants (bed_id);
alter table if exists bed_allocations add constraint FK4cg10og9xj2heudvxqehnl3bs foreign key (bed_id) references beds;
alter table if exists bed_allocations add constraint FKmi5lmxlctfxd6sc8wit64d8a2 foreign key (tenant_id) references tenants;
alter table if exists beds add constraint FK2tg7eb23xlsy3mkhcqlp15aha foreign key (room_id) references rooms;
alter table if exists complaints add constraint FK7ewgs5fsbf0x2sqrxwlg3x6xj foreign key (assignee_id) references users;
alter table if exists complaints add constraint FK9xux7hlo9krqlhae35or4px97 foreign key (property_id) references properties;
alter table if exists complaints add constraint FKmkd1v3j6dy5o73dt57llyspw5 foreign key (tenant_id) references tenants;
alter table if exists expenses add constraint FK9q2t88j6t59nlcm56ht8ml022 foreign key (property_id) references properties;
alter table if exists invoice_line_items add constraint FK62yq0tvg2ma4y8plfgx34bd3l foreign key (invoice_id) references invoices;
alter table if exists invoices add constraint FKj4hxeymbx9m0tow2vth0n1rh3 foreign key (property_id) references properties;
alter table if exists invoices add constraint FKld79gsqsmww43uddpxajoxts0 foreign key (tenant_id) references tenants;
alter table if exists kyc_documents add constraint FKitxj12fr7935w0ajud2lhem47 foreign key (tenant_id) references tenants;
alter table if exists kyc_documents add constraint FK88id0i0hi22bxqalvflhxkitg foreign key (verified_by) references users;
alter table if exists notices add constraint FKntrei71mnyo4hx6kbp6vg0cju foreign key (author_id) references users;
alter table if exists notices add constraint FK6hknqj24nu6b37anu0gt9w7w foreign key (property_id) references properties;
alter table if exists notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users;
alter table if exists payments add constraint FKrbqec6be74wab8iifh8g3i50i foreign key (invoice_id) references invoices;
alter table if exists properties add constraint FK73hpq2b49bw63rlbn8wi16qqs foreign key (manager_id) references users;
alter table if exists properties add constraint FKh7493invmcx1iy3od4lj1dtab foreign key (region_id) references regions;
alter table if exists property_amenities add constraint FKflie0u6fwgptlapkkqgpyh05 foreign key (property_id) references properties;
alter table if exists property_images add constraint FKemw5i1cysiorfaxfba7tgtpiu foreign key (property_id) references properties;
alter table if exists refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users;
alter table if exists refunds add constraint FK6gfrwx2g05fmxqam3ntm1oj5c foreign key (approved_by_id) references users;
alter table if exists refunds add constraint FKpt9ic0j1y6xwlej99wnynvnpy foreign key (payment_id) references payments;
alter table if exists regions add constraint FKc3t463iisd08sy45uwusu6ksm foreign key (region_manager_id) references users;
alter table if exists rooms add constraint FK35r032kwh410ggyqcbqrnhcut foreign key (property_id) references properties;
alter table if exists tenant_ledgers add constraint FK9eus983jfbdx2nx8xlxh0yrpd foreign key (invoice_id) references invoices;
alter table if exists tenant_ledgers add constraint FKrpqf5l4ung35kx4r4p5fq67da foreign key (payment_id) references payments;
alter table if exists tenant_ledgers add constraint FKexflxv7bs2emi39ufvb4jq3hy foreign key (tenant_id) references tenants;
alter table if exists tenants add constraint FKk8th17g1vlyfc098o3goye5f2 foreign key (bed_id) references beds;
alter table if exists tenants add constraint FKi3mqcyxxtcoi96p3qsfipxql8 foreign key (lead_id) references leads;
alter table if exists tenants add constraint FK1gbulcqli8dtngbforwml4n4l foreign key (user_id) references users;
